# Generated by Django 5.2 on 2025-04-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='download_count',
        ),
        migrations.AddField(
            model_name='book',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
