# Generated by Django 5.2 on 2025-04-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0004_remove_book_download_count_book_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics'), ('marathi', 'Marathi'), ('english', 'English'), ('history', 'History'), ('general', 'General Knowledge')], max_length=50),
        ),
    ]
